version: '3'
services: 
    # Run the Redis server container
    redis-server:
        # Docker CLI equivalent: docker run -d --name redis-server --network app-network redis
        image: 'redis'

    # Run the Node app container
    node-app:
        # Restarts unless it is explicitly stopped
        restart: always
        # Docker CLI equivalent for building the image: docker build -t node-app .
        build: .
        # Docker CLI equivalent for running the container: docker run -d --name node-app --network app-network -p 8081:8081 node-app
        ports:
            - "8081:8081"

# Note: The Docker CLI commands also require creating a network, which is not represented in the docker-compose file.
# Docker CLI for creating network: docker network create app-network
